// Adapted from https://github.com/rebane2001/mapartcraft, which is GPLv3.0
/*
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

const minecraft_color_vals = {
    //dark - normal - light

    UNDEFINED: [[0, 180, 0], [0, 220, 0], [0, 255, 0]], //used when a new block appears and this is outdated

    none: [[16, 16, 16]], //actually does not exist in MC

    grass: [[89, 125, 39], [109, 153, 48], [127, 178, 56]],
    sand: [[174, 164, 115], [213, 201, 140], [247, 233, 163]],
    cobweb: [[140, 140, 140], [171, 171, 171], [199, 199, 199]],
    tnt: [[180, 0, 0], [220, 0, 0], [255, 0, 0]],
    ice: [[112, 112, 180], [138, 138, 220], [160, 160, 255]],
    iron: [[117, 117, 117], [144, 144, 144], [167, 167, 167]],
    leaves: [[0, 87, 0], [0, 106, 0], [0, 124, 0]],
    clay: [[115, 118, 129], [141, 144, 158], [164, 168, 184]],
    dirt: [[106, 76, 54], [130, 94, 66], [151, 109, 77]],
    stone: [[79, 79, 79], [96, 96, 96], [112, 112, 112]],
    water: [[45, 45, 180], [55, 55, 220], [64, 64, 255]],
    oak: [[100, 84, 50], [123, 102, 62], [143, 119, 72]],
    diorite: [[180, 177, 172], [220, 217, 211], [255, 252, 245]],

    white: [[180, 180, 180], [220, 220, 220], [255, 255, 255]],
    orange: [[152, 89, 36], [186, 109, 44], [216, 127, 51]],
    magenta: [[125, 53, 152], [153, 65, 186], [178, 76, 216]],
    light_blue: [[72, 108, 152], [88, 132, 186], [102, 153, 216]],
    yellow: [[161, 161, 36], [197, 197, 44], [229, 229, 51]],
    lime: [[89, 144, 17], [109, 176, 21], [127, 204, 25]],
    pink: [[170, 89, 116], [208, 109, 142], [242, 127, 165]],
    gray: [[53, 53, 53], [65, 65, 65], [76, 76, 76]],
    light_gray: [[108, 108, 108], [132, 132, 132], [153, 153, 153]],
    cyan: [[53, 89, 108], [65, 109, 132], [76, 127, 153]],
    purple: [[89, 44, 125], [109, 54, 153], [127, 63, 178]],
    blue: [[36, 53, 125], [44, 65, 153], [51, 76, 178]],
    brown: [[72, 53, 36], [88, 65, 44], [102, 76, 51]],
    green: [[72, 89, 36], [88, 109, 44], [102, 127, 51]],
    red: [[108, 36, 36], [132, 44, 44], [153, 51, 51]],
    black: [[17, 17, 17], [21, 21, 21], [25, 25, 25]],

    gold: [[176, 168, 54], [215, 205, 66], [250, 238, 77]],
    diamond: [[64, 154, 150], [79, 188, 183], [92, 219, 213]],
    lapis: [[52, 90, 180], [63, 110, 220], [74, 128, 255]],
    emerald: [[0, 153, 40], [0, 187, 50], [0, 217, 58]],

    spruce: [[91, 60, 34], [111, 74, 42], [129, 86, 49]],

    netherrack: [[79, 1, 0], [96, 1, 0], [112, 2, 0]],

    white_terracotta: [[147, 124, 113], [180, 152, 138], [209, 177, 161]],
    orange_terracotta: [[112, 57, 25], [137, 70, 31], [159, 82, 36]],
    magenta_terracotta: [[105, 61, 76], [128, 75, 93], [149, 87, 108]],
    light_blue_terracotta: [[79, 76, 97], [96, 93, 119], [112, 108, 138]],
    yellow_terracotta: [[131, 93, 25], [160, 114, 31], [186, 133, 36]],
    lime_terracotta: [[72, 82, 37], [88, 100, 45], [103, 117, 53]],
    pink_terracotta: [[112, 54, 55], [138, 66, 67], [160, 77, 78]],
    gray_terracotta: [[40, 28, 24], [49, 35, 30], [57, 41, 35]],
    light_gray_terracotta: [[95, 75, 69], [116, 92, 84], [135, 107, 98]],
    cyan_terracotta: [[61, 64, 64], [75, 79, 79], [87, 92, 92]],
    purple_terracotta: [[86, 51, 62], [105, 62, 75], [122, 73, 88]],
    blue_terracotta: [[53, 43, 64], [65, 53, 79], [76, 62, 92]],
    brown_terracotta: [[53, 35, 24], [65, 43, 30], [76, 50, 35]],
    green_terracotta: [[53, 57, 29], [65, 70, 36], [76, 82, 42]],
    red_terracotta: [[100, 42, 32], [122, 51, 39], [142, 60, 46]],
    black_terracotta: [[26, 15, 11], [31, 18, 13], [37, 22, 16]],

    crimson_nylium: [[133, 33, 34], [163, 41, 42], [189, 48, 49]],
    crimson_stem: [[104, 44, 68], [127, 54, 83], [148, 63, 97]],
    crimson_hyphae: [[64, 17, 20], [79, 21, 25], [92, 25, 29]],

    warped_nylium: [[15, 88, 94], [18, 108, 115], [22, 126, 134]],
    warped_stem: [[40, 100, 98], [50, 122, 120], [58, 142, 140]],
    warped_hyphae: [[60, 31, 43], [74, 37, 53], [86, 44, 62]],
    warped_wart_block: [[14, 127, 93], [17, 155, 114], [20, 180, 133]],

    deepslate: [[70, 70, 70], [86, 86, 86], [100, 100, 100]],

    raw_iron_block: [[152, 123, 103], [186, 150, 126], [216, 175, 147]],

    glow_lichen: [[89, 117, 105], [109, 144, 129], [127, 167, 150]],
}

export const MINECRAFT_COLORS = new Map([
    ['UNDEFINED', minecraft_color_vals.UNDEFINED],
    ['TRANSPARENT', minecraft_color_vals.TRANSPARENT],

    ['redstone_lamp', minecraft_color_vals.none],
    ['cake', minecraft_color_vals.none],
    ['candle_cake', minecraft_color_vals.none],
    ['white_candle_cake', minecraft_color_vals.none],
    ['orange_candle_cake', minecraft_color_vals.none],
    ['magenta_candle_cake', minecraft_color_vals.none],
    ['light_blue_candle_cake', minecraft_color_vals.none],
    ['yellow_candle_cake', minecraft_color_vals.none],
    ['lime_candle_cake', minecraft_color_vals.none],
    ['pink_candle_cake', minecraft_color_vals.none],
    ['gray_candle_cake', minecraft_color_vals.none],
    ['light_gray_candle_cake', minecraft_color_vals.none],
    ['cyan_candle_cake', minecraft_color_vals.none],
    ['purple_candle_cake', minecraft_color_vals.none],
    ['blue_candle_cake', minecraft_color_vals.none],
    ['brown_candle_cake', minecraft_color_vals.none],
    ['green_candle_cake', minecraft_color_vals.none],
    ['red_candle_cake', minecraft_color_vals.none],
    ['black_candle_cake', minecraft_color_vals.none],
    ['powered_rail', minecraft_color_vals.none],
    ['detector_rail', minecraft_color_vals.none],
    ['torch', minecraft_color_vals.none],
    ['wall_torch', minecraft_color_vals.none],
    ['soul_torch', minecraft_color_vals.none],
    ['soul_wall_torch', minecraft_color_vals.none],
    ['redstone_wire', minecraft_color_vals.none],
    ['ladder', minecraft_color_vals.none],
    ['rail', minecraft_color_vals.none],
    ['lever', minecraft_color_vals.none],
    ['redstone_torch', minecraft_color_vals.none],
    ['redstone_wall_torch', minecraft_color_vals.none],
    ['stone_button', minecraft_color_vals.none],
    ['polished_blackstone_button', minecraft_color_vals.none],
    ['oak_button', minecraft_color_vals.none],
    ['spruce_button', minecraft_color_vals.none],
    ['birch_button', minecraft_color_vals.none],
    ['jungle_button', minecraft_color_vals.none],
    ['acacia_button', minecraft_color_vals.none],
    ['cherry_button', minecraft_color_vals.none],
    ['dark_oak_button', minecraft_color_vals.none],
    ['mangrove_button', minecraft_color_vals.none],
    ['crimson_button', minecraft_color_vals.none],
    ['warped_button', minecraft_color_vals.none],
    ['repeater', minecraft_color_vals.none],
    ['tripwire_hook', minecraft_color_vals.none],
    ['tripwire', minecraft_color_vals.none],
    ['flower_pot', minecraft_color_vals.none],
    ['potted_dandelion', minecraft_color_vals.none],
    ['potted_poppy', minecraft_color_vals.none],
    ['potted_blue_orchid', minecraft_color_vals.none],
    ['potted_allium', minecraft_color_vals.none],
    ['potted_azure_bluet', minecraft_color_vals.none],
    ['potted_red_tulip', minecraft_color_vals.none],
    ['potted_orange_tulip', minecraft_color_vals.none],
    ['potted_white_tulip', minecraft_color_vals.none],
    ['potted_pink_tulip', minecraft_color_vals.none],
    ['potted_oxeye_daisy', minecraft_color_vals.none],
    ['potted_cornflower', minecraft_color_vals.none],
    ['potted_lily_of_the_valley', minecraft_color_vals.none],
    ['potted_wither_rose', minecraft_color_vals.none],
    ['potted_oak_sapling', minecraft_color_vals.none],
    ['potted_spruce_sapling', minecraft_color_vals.none],
    ['potted_birch_sapling', minecraft_color_vals.none],
    ['potted_jungle_sapling', minecraft_color_vals.none],
    ['potted_acacia_sapling', minecraft_color_vals.none],
    ['potted_cherry_sapling', minecraft_color_vals.none],
    ['potted_dark_oak_sapling', minecraft_color_vals.none],
    ['potted_red_mushroom', minecraft_color_vals.none],
    ['potted_brown_mushroom', minecraft_color_vals.none],
    ['potted_fern', minecraft_color_vals.none],
    ['potted_dead_bush', minecraft_color_vals.none],
    ['potted_cactus', minecraft_color_vals.none],
    ['potted_bamboo', minecraft_color_vals.none],
    ['potted_azalea_bush', minecraft_color_vals.none],
    ['potted_flowering_azalea_bush', minecraft_color_vals.none],
    ['potted_crimson_fungus', minecraft_color_vals.none],
    ['potted_warped_fungus', minecraft_color_vals.none],
    ['potted_crimson_roots', minecraft_color_vals.none],
    ['potted_warped_roots', minecraft_color_vals.none],
    ['potted_mangrove_propagule', minecraft_color_vals.none],
    ['potted_torchflower', minecraft_color_vals.none],
    ['skeleton_skull', minecraft_color_vals.none],
    ['wither_skeleton_skull', minecraft_color_vals.none],
    ['zombie_head', minecraft_color_vals.none],
    ['player_head', minecraft_color_vals.none],
    ['creeper_head', minecraft_color_vals.none],
    ['dragon_head', minecraft_color_vals.none],
    ['skeleton_wall_skull', minecraft_color_vals.none],
    ['wither_skeleton_wall_skull', minecraft_color_vals.none],
    ['zombie_wall_head', minecraft_color_vals.none],
    ['player_wall_head', minecraft_color_vals.none],
    ['creeper_wall_head', minecraft_color_vals.none],
    ['dragon_wall_head', minecraft_color_vals.none],
    ['comparator', minecraft_color_vals.none],
    ['activator_rail', minecraft_color_vals.none],
    ['end_rod', minecraft_color_vals.none],
    ['glass', minecraft_color_vals.none],
    ['glass_pane', minecraft_color_vals.none],
    ['white_stained_glass_pane', minecraft_color_vals.none],
    ['orange_stained_glass_pane', minecraft_color_vals.none],
    ['magenta_stained_glass_pane', minecraft_color_vals.none],
    ['light_blue_stained_glass_pane', minecraft_color_vals.none],
    ['yellow_stained_glass_pane', minecraft_color_vals.none],
    ['lime_stained_glass_pane', minecraft_color_vals.none],
    ['pink_stained_glass_pane', minecraft_color_vals.none],
    ['gray_stained_glass_pane', minecraft_color_vals.none],
    ['light_gray_stained_glass_pane', minecraft_color_vals.none],
    ['cyan_stained_glass_pane', minecraft_color_vals.none],
    ['purple_stained_glass_pane', minecraft_color_vals.none],
    ['blue_stained_glass_pane', minecraft_color_vals.none],
    ['brown_stained_glass_pane', minecraft_color_vals.none],
    ['green_stained_glass_pane', minecraft_color_vals.none],
    ['red_stained_glass_pane', minecraft_color_vals.none],
    ['black_stained_glass_pane', minecraft_color_vals.none],
    ['nether_portal', minecraft_color_vals.none],
    ['structure_void', minecraft_color_vals.none],
    ['light', minecraft_color_vals.none],
    ['iron_bars', minecraft_color_vals.none],
    ['chain', minecraft_color_vals.none],

    ['grass_block', minecraft_color_vals.grass],
    ['slime_block', minecraft_color_vals.grass],

    ['sand', minecraft_color_vals.sand],
    ['suspicious_sand', minecraft_color_vals.sand],
    ['sandstone', minecraft_color_vals.sand],
    ['sandstone_slab', minecraft_color_vals.sand],
    ['sandstone_stairs', minecraft_color_vals.sand],
    ['sandstone_wall', minecraft_color_vals.sand],
    ['birch_log[axis=y]', minecraft_color_vals.sand],
    ['birch_planks', minecraft_color_vals.sand],
    ['birch_slab', minecraft_color_vals.sand],
    ['stripped_birch_log', minecraft_color_vals.sand],
    ['birch_wood', minecraft_color_vals.sand],
    ['stripped_birch_wood', minecraft_color_vals.sand],
    ['birch_sign', minecraft_color_vals.sand],
    ['birch_wall_sign', minecraft_color_vals.sand],
    ['birch_hanging_sign', minecraft_color_vals.sand],
    ['birch_wall_hanging_sign', minecraft_color_vals.sand],
    ['birch_pressure_plate', minecraft_color_vals.sand],
    ['birch_trapdoor', minecraft_color_vals.sand],
    ['birch_stairs', minecraft_color_vals.sand],
    ['birch_fence_gate', minecraft_color_vals.sand],
    ['birch_fence', minecraft_color_vals.sand],
    ['birch_door', minecraft_color_vals.sand],
    ['glowstone', minecraft_color_vals.sand],
    ['end_stone', minecraft_color_vals.sand],
    ['end_stone_bricks', minecraft_color_vals.sand],
    ['end_stone_brick_slab', minecraft_color_vals.sand],
    ['end_stone_brick_wall', minecraft_color_vals.sand],
    ['end_stone_brick_stairs', minecraft_color_vals.sand],
    ['bone_block', minecraft_color_vals.sand],
    ['cut_sandstone', minecraft_color_vals.sand],
    ['cut_sandstone_slab', minecraft_color_vals.sand],
    ['chiseled_sandstone', minecraft_color_vals.sand],
    ['smooth_sandstone', minecraft_color_vals.sand],
    ['smooth_sandstone_stairs', minecraft_color_vals.sand],
    ['smooth_sandstone_slab', minecraft_color_vals.sand],
    ['turtle_egg', minecraft_color_vals.sand],
    ['scaffolding', minecraft_color_vals.sand],
    ['candle', minecraft_color_vals.sand],
    ['ochre_froglight', minecraft_color_vals.sand],

    ['cobweb', minecraft_color_vals.cobweb],
    ['mushroom_stem', minecraft_color_vals.cobweb],
    ['white_bed[part=head]', minecraft_color_vals.cobweb],
    ['orange_bed[part=head]', minecraft_color_vals.cobweb],
    ['magenta_bed[part=head]', minecraft_color_vals.cobweb],
    ['light_blue_bed[part=head]', minecraft_color_vals.cobweb],
    ['yellow_bed[part=head]', minecraft_color_vals.cobweb],
    ['lime_bed[part=head]', minecraft_color_vals.cobweb],
    ['pink_bed[part=head]', minecraft_color_vals.cobweb],
    ['gray_bed[part=head]', minecraft_color_vals.cobweb],
    ['light_gray_bed[part=head]', minecraft_color_vals.cobweb],
    ['cyan_bed[part=head]', minecraft_color_vals.cobweb],
    ['purple_bed[part=head]', minecraft_color_vals.cobweb],
    ['blue_bed[part=head]', minecraft_color_vals.cobweb],
    ['brown_bed[part=head]', minecraft_color_vals.cobweb],
    ['green_bed[part=head]', minecraft_color_vals.cobweb],
    ['red_bed[part=head]', minecraft_color_vals.cobweb],
    ['black_bed[part=head]', minecraft_color_vals.cobweb],
    ['white_candle', minecraft_color_vals.cobweb],

    ['tnt', minecraft_color_vals.tnt],
    ['redstone_block', minecraft_color_vals.tnt],
    ['lava', minecraft_color_vals.tnt],
    ['fire', minecraft_color_vals.tnt],

    ['ice', minecraft_color_vals.ice],
    ['packed_ice', minecraft_color_vals.ice],
    ['blue_ice', minecraft_color_vals.ice],
    ['frosted_ice', minecraft_color_vals.ice],

    ['iron_block', minecraft_color_vals.iron],
    ['iron_trapdoor', minecraft_color_vals.iron],
    ['iron_door', minecraft_color_vals.iron],
    ['iron_trapdoor', minecraft_color_vals.iron],
    ['heavy_weighted_pressure_plate', minecraft_color_vals.iron],
    ['brewing_stand', minecraft_color_vals.iron],
    ['lantern', minecraft_color_vals.iron],
    ['soul_lantern', minecraft_color_vals.iron],
    ['anvil', minecraft_color_vals.iron],
    ['grindstone', minecraft_color_vals.iron],
    ['lodestone', minecraft_color_vals.iron],
    ['heavy_core', minecraft_color_vals.iron],

    ['oak_leaves', minecraft_color_vals.leaves],
    ['spruce_leaves', minecraft_color_vals.leaves],
    ['birch_leaves', minecraft_color_vals.leaves],
    ['jungle_leaves', minecraft_color_vals.leaves],
    ['acacia_leaves', minecraft_color_vals.leaves],
    ['dark_oak_leaves', minecraft_color_vals.leaves],
    ['mangrove_leaves', minecraft_color_vals.leaves],
    ['azalea_leaves', minecraft_color_vals.leaves],
    ['flowering_azalea_leaves', minecraft_color_vals.leaves],
    ['oak_sapling', minecraft_color_vals.leaves],
    ['spruce_sapling', minecraft_color_vals.leaves],
    ['birch_sapling', minecraft_color_vals.leaves],
    ['jungle_sapling', minecraft_color_vals.leaves],
    ['acacia_sapling', minecraft_color_vals.leaves],
    ['dark_oak_sapling', minecraft_color_vals.leaves],
    ['mangrove_propagule', minecraft_color_vals.leaves],
    ['dandelion', minecraft_color_vals.leaves],
    ['poppy', minecraft_color_vals.leaves],
    ['blue_orchid', minecraft_color_vals.leaves],
    ['allium', minecraft_color_vals.leaves],
    ['azure_bluet', minecraft_color_vals.leaves],
    ['red_tulip', minecraft_color_vals.leaves],
    ['orange_tulip', minecraft_color_vals.leaves],
    ['white_tulip', minecraft_color_vals.leaves],
    ['pink_tulip', minecraft_color_vals.leaves],
    ['oxeye_daisy', minecraft_color_vals.leaves],
    ['cornflower', minecraft_color_vals.leaves],
    ['lily_of_the_valley', minecraft_color_vals.leaves],
    ['wither_rose', minecraft_color_vals.leaves],
    ['sunflower', minecraft_color_vals.leaves],
    ['lilac', minecraft_color_vals.leaves],
    ['rose_bush', minecraft_color_vals.leaves],
    ['peony', minecraft_color_vals.leaves],
    ['wheat', minecraft_color_vals.leaves],
    ['sugar_cane', minecraft_color_vals.leaves],
    ['pumpkin_stem', minecraft_color_vals.leaves],
    ['attached_pumpkin_stem', minecraft_color_vals.leaves],
    ['melon_stem', minecraft_color_vals.leaves],
    ['attached_melon_stem', minecraft_color_vals.leaves],
    ['lily_pad', minecraft_color_vals.leaves],
    ['cocoa', minecraft_color_vals.leaves],
    ['carrots', minecraft_color_vals.leaves],
    ['potatoes', minecraft_color_vals.leaves],
    ['beetroots', minecraft_color_vals.leaves],
    ['sweet_berry_bush', minecraft_color_vals.leaves],
    ['grass', minecraft_color_vals.leaves],
    ['short_grass', minecraft_color_vals.leaves],
    ['fern', minecraft_color_vals.leaves],
    ['tall_grass', minecraft_color_vals.leaves],
    ['large_fern', minecraft_color_vals.leaves],
    ['vine', minecraft_color_vals.leaves],
    ['cactus', minecraft_color_vals.leaves],
    ['bamboo', minecraft_color_vals.leaves],
    ['cave_vines', minecraft_color_vals.leaves],
    ['cave_vines_plant', minecraft_color_vals.leaves],
    ['spore_blossom', minecraft_color_vals.leaves],
    ['azalea', minecraft_color_vals.leaves],
    ['flowering_azalea', minecraft_color_vals.leaves],
    ['big_dripleaf', minecraft_color_vals.leaves],
    ['big_dripleaf_stem', minecraft_color_vals.leaves],
    ['small_dripleaf', minecraft_color_vals.leaves],
    ['torchflower', minecraft_color_vals.leaves],
    ['torchflower_crop', minecraft_color_vals.leaves],
    ['pitcher_crop', minecraft_color_vals.leaves],
    ['pitcher_plant', minecraft_color_vals.leaves],
    ['pink_petals', minecraft_color_vals.leaves],

    ['clay', minecraft_color_vals.clay],
    ['infested_stone', minecraft_color_vals.clay],
    ['infested_cobblestone', minecraft_color_vals.clay],
    ['infested_stone_bricks', minecraft_color_vals.clay],
    ['infested_cracked_stone_bricks', minecraft_color_vals.clay],
    ['infested_mossy_stone_bricks', minecraft_color_vals.clay],
    ['infested_chiseled_stone_bricks', minecraft_color_vals.clay],

    ['jungle_log[axis=y]', minecraft_color_vals.dirt],
    ['jungle_planks', minecraft_color_vals.dirt],
    ['jungle_slab', minecraft_color_vals.dirt],
    ['stripped_jungle_log', minecraft_color_vals.dirt],
    ['jungle_wood', minecraft_color_vals.dirt],
    ['stripped_jungle_wood', minecraft_color_vals.dirt],
    ['jungle_sign', minecraft_color_vals.dirt],
    ['jungle_wall_sign', minecraft_color_vals.dirt],
    ['jungle_hanging_sign', minecraft_color_vals.dirt],
    ['jungle_wall_hanging_sign', minecraft_color_vals.dirt],
    ['jungle_pressure_plate', minecraft_color_vals.dirt],
    ['jungle_trapdoor', minecraft_color_vals.dirt],
    ['jungle_stairs', minecraft_color_vals.dirt],
    ['jungle_fence_gate', minecraft_color_vals.dirt],
    ['jungle_fence', minecraft_color_vals.dirt],
    ['jungle_door', minecraft_color_vals.dirt],
    ['dirt', minecraft_color_vals.dirt],
    ['coarse_dirt', minecraft_color_vals.dirt],
    ['rooted_dirt', minecraft_color_vals.dirt],
    ['farmland', minecraft_color_vals.dirt],
    ['dirt_path', minecraft_color_vals.dirt],
    ['jukebox', minecraft_color_vals.dirt],
    ['granite', minecraft_color_vals.dirt],
    ['granite_slab', minecraft_color_vals.dirt],
    ['granite_wall', minecraft_color_vals.dirt],
    ['granite_stairs', minecraft_color_vals.dirt],
    ['polished_granite', minecraft_color_vals.dirt],
    ['polished_granite_slab', minecraft_color_vals.dirt],
    ['polished_granite_stairs', minecraft_color_vals.dirt],
    ['brown_mushroom_block', minecraft_color_vals.dirt],
    ['hanging_roots', minecraft_color_vals.dirt],
    ['packed_mud', minecraft_color_vals.dirt],

    ['cobblestone', minecraft_color_vals.stone],
    ['cobblestone_slab', minecraft_color_vals.stone],
    ['cobblestone_stairs', minecraft_color_vals.stone],
    ['cobblestone_wall', minecraft_color_vals.stone],
    ['mossy_cobblestone', minecraft_color_vals.stone],
    ['mossy_cobblestone_slab', minecraft_color_vals.stone],
    ['mossy_cobblestone_wall', minecraft_color_vals.stone],
    ['mossy_cobblestone_stairs', minecraft_color_vals.stone],
    ['mossy_stone_bricks', minecraft_color_vals.stone],
    ['mossy_stone_brick_wall', minecraft_color_vals.stone],
    ['mossy_stone_brick_stairs', minecraft_color_vals.stone],
    ['mossy_stone_brick_slab', minecraft_color_vals.stone],
    ['cracked_stone_bricks', minecraft_color_vals.stone],
    ['chiseled_stone_bricks', minecraft_color_vals.stone],
    ['stone', minecraft_color_vals.stone],
    ['stone_slab', minecraft_color_vals.stone],
    ['stone_stairs', minecraft_color_vals.stone],
    ['stone_pressure_plate', minecraft_color_vals.stone],
    ['smooth_stone', minecraft_color_vals.stone],
    ['smooth_stone_slab', minecraft_color_vals.stone],
    ['stone_bricks', minecraft_color_vals.stone],
    ['stone_brick_slab', minecraft_color_vals.stone],
    ['stone_brick_stairs', minecraft_color_vals.stone],
    ['stone_brick_wall', minecraft_color_vals.stone],
    ['andesite', minecraft_color_vals.stone],
    ['andesite_slab', minecraft_color_vals.stone],
    ['andesite_stairs', minecraft_color_vals.stone],
    ['polished_andesite', minecraft_color_vals.stone],
    ['polished_andesite_slab', minecraft_color_vals.stone],
    ['polished_andesite_stairs', minecraft_color_vals.stone],
    ['bedrock', minecraft_color_vals.stone],
    ['acacia_log', minecraft_color_vals.stone],
    ['gravel', minecraft_color_vals.stone],
    ['suspicious_gravel', minecraft_color_vals.stone],
    ['gold_ore', minecraft_color_vals.stone],
    ['iron_ore', minecraft_color_vals.stone],
    ['coal_ore', minecraft_color_vals.stone],
    ['lapis_ore', minecraft_color_vals.stone],
    ['diamond_ore', minecraft_color_vals.stone],
    ['redstone_ore', minecraft_color_vals.stone],
    ['emerald_ore', minecraft_color_vals.stone],
    ['copper_ore', minecraft_color_vals.stone],
    ['dispenser', minecraft_color_vals.stone],
    ['dropper', minecraft_color_vals.stone],
    ['observer', minecraft_color_vals.stone],
    ['spawner', minecraft_color_vals.stone],
    ['furnace', minecraft_color_vals.stone],
    ['blast_furnace', minecraft_color_vals.stone],
    ['smoker', minecraft_color_vals.stone],
    ['ender_chest', minecraft_color_vals.stone],
    ['stonecutter', minecraft_color_vals.stone],
    ['piston', minecraft_color_vals.stone],
    ['sticky_piston', minecraft_color_vals.stone],
    ['piston_head', minecraft_color_vals.stone],
    ['moving_piston', minecraft_color_vals.stone],
    ['cauldron', minecraft_color_vals.stone],
    ['lava_cauldron', minecraft_color_vals.stone],
    ['powder_snow_cauldron', minecraft_color_vals.stone],
    ['water_cauldron', minecraft_color_vals.stone],
    ['hopper', minecraft_color_vals.stone],
    ['crafter', minecraft_color_vals.stone],
    ['trial_spawner', minecraft_color_vals.stone],
    ['vault', minecraft_color_vals.stone],

    ['water', minecraft_color_vals.water],
    ['kelp', minecraft_color_vals.water],
    ['kelp_plant', minecraft_color_vals.water],
    ['seagrass', minecraft_color_vals.water],
    ['tall_seagrass', minecraft_color_vals.water],
    ['bubble_column', minecraft_color_vals.water],
    ['oak_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['spruce_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['birch_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['jungle_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['acacia_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['dark_oak_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['mangrove_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['azalea_leaves[waterlogged=true]', minecraft_color_vals.water],
    ['flowering_azalea_leaves[waterlogged=true]', minecraft_color_vals.water],

    ['oak_log[axis=y]', minecraft_color_vals.oak],
    ['oak_planks', minecraft_color_vals.oak],
    ['oak_slab', minecraft_color_vals.oak],
    ['stripped_oak_log', minecraft_color_vals.oak],
    ['oak_wood', minecraft_color_vals.oak],
    ['stripped_oak_wood', minecraft_color_vals.oak],
    ['oak_sign', minecraft_color_vals.oak],
    ['oak_wall_sign', minecraft_color_vals.oak],
    ['oak_hanging_sign', minecraft_color_vals.oak],
    ['oak_wall_hanging_sign', minecraft_color_vals.oak],
    ['oak_pressure_plate', minecraft_color_vals.oak],
    ['oak_trapdoor', minecraft_color_vals.oak],
    ['oak_stairs', minecraft_color_vals.oak],
    ['oak_fence_gate', minecraft_color_vals.oak],
    ['oak_fence', minecraft_color_vals.oak],
    ['oak_door', minecraft_color_vals.oak],
    ['spruce_wall_hanging_sign', minecraft_color_vals.oak], //weird
    ['crafting_table', minecraft_color_vals.oak],
    ['note_block', minecraft_color_vals.oak],
    ['bookshelf', minecraft_color_vals.oak],
    ['chest', minecraft_color_vals.oak],
    ['trapped_chest', minecraft_color_vals.oak],
    ['daylight_detector', minecraft_color_vals.oak],
    ['loom', minecraft_color_vals.oak],
    ['barrel', minecraft_color_vals.oak],
    ['cartography_table', minecraft_color_vals.oak],
    ['fletching_table', minecraft_color_vals.oak],
    ['lectern', minecraft_color_vals.oak],
    ['smithing_table', minecraft_color_vals.oak],
    ['composter', minecraft_color_vals.oak],
    ['bamboo_sapling', minecraft_color_vals.oak],
    ['dead_bush', minecraft_color_vals.oak],
    ['petrified_oak_slab', minecraft_color_vals.oak],
    ['beehive', minecraft_color_vals.oak],
    ['white_banner', minecraft_color_vals.oak],
    ['orange_banner', minecraft_color_vals.oak],
    ['magenta_banner', minecraft_color_vals.oak],
    ['light_blue_banner', minecraft_color_vals.oak],
    ['yellow_banner', minecraft_color_vals.oak],
    ['lime_banner', minecraft_color_vals.oak],
    ['pink_banner', minecraft_color_vals.oak],
    ['gray_banner', minecraft_color_vals.oak],
    ['light_gray_banner', minecraft_color_vals.oak],
    ['cyan_banner', minecraft_color_vals.oak],
    ['purple_banner', minecraft_color_vals.oak],
    ['blue_banner', minecraft_color_vals.oak],
    ['brown_banner', minecraft_color_vals.oak],
    ['green_banner', minecraft_color_vals.oak],
    ['red_banner', minecraft_color_vals.oak],
    ['black_banner', minecraft_color_vals.oak],
    ['white_wall_banner', minecraft_color_vals.oak],
    ['orange_wall_banner', minecraft_color_vals.oak],
    ['magenta_wall_banner', minecraft_color_vals.oak],
    ['light_blue_wall_banner', minecraft_color_vals.oak],
    ['yellow_wall_banner', minecraft_color_vals.oak],
    ['lime_wall_banner', minecraft_color_vals.oak],
    ['pink_wall_banner', minecraft_color_vals.oak],
    ['gray_wall_banner', minecraft_color_vals.oak],
    ['light_gray_wall_banner', minecraft_color_vals.oak],
    ['cyan_wall_banner', minecraft_color_vals.oak],
    ['purple_wall_banner', minecraft_color_vals.oak],
    ['blue_wall_banner', minecraft_color_vals.oak],
    ['brown_wall_banner', minecraft_color_vals.oak],
    ['green_wall_banner', minecraft_color_vals.oak],
    ['red_wall_banner', minecraft_color_vals.oak],
    ['black_wall_banner', minecraft_color_vals.oak],

    ['birch_log', minecraft_color_vals.diorite],
    ['diorite', minecraft_color_vals.diorite],
    ['diorite_slab', minecraft_color_vals.diorite],
    ['diorite_stairs', minecraft_color_vals.diorite],
    ['diorite_wall', minecraft_color_vals.diorite],
    ['polished_diorite', minecraft_color_vals.diorite],
    ['polished_diorite_slab', minecraft_color_vals.diorite],
    ['polished_diorite_stairs', minecraft_color_vals.diorite],
    ['quartz_block', minecraft_color_vals.diorite],
    ['quartz_slab', minecraft_color_vals.diorite],
    ['quartz_stairs', minecraft_color_vals.diorite],
    ['smooth_quartz', minecraft_color_vals.diorite],
    ['smooth_quartz_slab', minecraft_color_vals.diorite],
    ['smooth_quartz_stairs', minecraft_color_vals.diorite],
    ['chiseled_quartz_block', minecraft_color_vals.diorite],
    ['quartz_bricks', minecraft_color_vals.diorite],
    ['quartz_pillar', minecraft_color_vals.diorite],
    ['sea_lantern', minecraft_color_vals.diorite],
    ['target', minecraft_color_vals.diorite],

    ['white_wool', minecraft_color_vals.white],
    ['white_carpet', minecraft_color_vals.white],
    ['white_stained_glass', minecraft_color_vals.white],
    ['white_concrete', minecraft_color_vals.white],
    ['white_concrete_powder', minecraft_color_vals.white],
    ['white_glazed_terracotta', minecraft_color_vals.white],
    ['snow_block', minecraft_color_vals.white],
    ['snow', minecraft_color_vals.white],
    ['powder_snow', minecraft_color_vals.white],
    ['white_bed[part=foot]', minecraft_color_vals.white],
    ['white_shulker_box', minecraft_color_vals.white],

    ['orange_wool', minecraft_color_vals.orange],
    ['orange_carpet', minecraft_color_vals.orange],
    ['orange_stained_glass', minecraft_color_vals.orange],
    ['orange_concrete', minecraft_color_vals.orange],
    ['orange_concrete_powder', minecraft_color_vals.orange],
    ['orange_glazed_terracotta', minecraft_color_vals.orange],
    ['orange_bed[part=foot]', minecraft_color_vals.orange],
    ['orange_shulker_box', minecraft_color_vals.orange],
    ['orange_candle', minecraft_color_vals.orange],
    ['pumpkin', minecraft_color_vals.orange],
    ['carved_pumpkin', minecraft_color_vals.orange],
    ['jack_o_lantern', minecraft_color_vals.orange],
    ['acacia_log[axis=y]', minecraft_color_vals.orange],
    ['acacia_planks', minecraft_color_vals.orange],
    ['acacia_slab', minecraft_color_vals.orange],
    ['stripped_acacia_log', minecraft_color_vals.orange],
    ['stripped_acacia_wood', minecraft_color_vals.orange],
    ['acacia_sign', minecraft_color_vals.orange],
    ['acacia_wall_sign', minecraft_color_vals.orange],
    ['acacia_hanging_sign', minecraft_color_vals.orange],
    ['acacia_wall_hanging_sign', minecraft_color_vals.orange],
    ['acacia_pressure_plate', minecraft_color_vals.orange],
    ['acacia_trapdoor', minecraft_color_vals.orange],
    ['acacia_stairs', minecraft_color_vals.orange],
    ['acacia_fence_gate', minecraft_color_vals.orange],
    ['acacia_fence', minecraft_color_vals.orange],
    ['acacia_door', minecraft_color_vals.orange],
    ['red_sand', minecraft_color_vals.orange],
    ['red_sandstone', minecraft_color_vals.orange],
    ['red_sandstone_slab', minecraft_color_vals.orange],
    ['red_sandstone_stairs', minecraft_color_vals.orange],
    ['red_sandstone_wall', minecraft_color_vals.orange],
    ['cut_red_sandstone', minecraft_color_vals.orange],
    ['cut_red_sandstone_slab', minecraft_color_vals.orange],
    ['chiseled_red_sandstone', minecraft_color_vals.orange],
    ['smooth_red_sandstone', minecraft_color_vals.orange],
    ['smooth_red_sandstone_stairs', minecraft_color_vals.orange],
    ['smooth_red_sandstone_slab', minecraft_color_vals.orange],
    ['terracotta', minecraft_color_vals.orange],
    ['honey_block', minecraft_color_vals.orange],
    ['honeycomb_block', minecraft_color_vals.orange],
    ['raw_copper_block', minecraft_color_vals.orange],
    ['copper_block', minecraft_color_vals.orange],
    ['cut_copper', minecraft_color_vals.orange],
    ['cut_copper_slab', minecraft_color_vals.orange],
    ['cut_copper_stairs', minecraft_color_vals.orange],
    ['waxed_copper_block', minecraft_color_vals.orange],
    ['waxed_cut_copper', minecraft_color_vals.orange],
    ['waxed_cut_copper_slab', minecraft_color_vals.orange],
    ['waxed_cut_copper_stairs', minecraft_color_vals.orange],
    ['lightning_rod', minecraft_color_vals.orange],

    ['magenta_wool', minecraft_color_vals.magenta],
    ['magenta_carpet', minecraft_color_vals.magenta],
    ['magenta_stained_glass', minecraft_color_vals.magenta],
    ['magenta_concrete', minecraft_color_vals.magenta],
    ['magenta_concrete_powder', minecraft_color_vals.magenta],
    ['magenta_glazed_terracotta', minecraft_color_vals.magenta],
    ['magenta_bed[part=foot]', minecraft_color_vals.magenta],
    ['magenta_shulker_box', minecraft_color_vals.magenta],
    ['magenta_candle', minecraft_color_vals.magenta],
    ['purpur_block', minecraft_color_vals.magenta],
    ['purpur_slab', minecraft_color_vals.magenta],
    ['purpur_stairs', minecraft_color_vals.magenta],
    ['purpur_pillar', minecraft_color_vals.magenta],

    ['light_blue_wool', minecraft_color_vals.light_blue],
    ['light_blue_carpet', minecraft_color_vals.light_blue],
    ['light_blue_stained_glass', minecraft_color_vals.light_blue],
    ['light_blue_concrete', minecraft_color_vals.light_blue],
    ['light_blue_concrete_powder', minecraft_color_vals.light_blue],
    ['light_blue_glazed_terracotta', minecraft_color_vals.light_blue],
    ['light_blue_bed[part=foot]', minecraft_color_vals.light_blue],
    ['light_blue_shulker_box', minecraft_color_vals.light_blue],
    ['light_blue_candle', minecraft_color_vals.light_blue],
    ['soul_fire', minecraft_color_vals.light_blue],

    ['yellow_wool', minecraft_color_vals.yellow],
    ['yellow_carpet', minecraft_color_vals.yellow],
    ['yellow_stained_glass', minecraft_color_vals.yellow],
    ['yellow_concrete', minecraft_color_vals.yellow],
    ['yellow_concrete_powder', minecraft_color_vals.yellow],
    ['yellow_glazed_terracotta', minecraft_color_vals.yellow],
    ['yellow_bed[part=foot]', minecraft_color_vals.yellow],
    ['yellow_shulker_box', minecraft_color_vals.yellow],
    ['yellow_candle', minecraft_color_vals.yellow],
    ['hay_block', minecraft_color_vals.yellow],
    ['sponge', minecraft_color_vals.yellow],
    ['wet_sponge', minecraft_color_vals.yellow],
    ['horn_coral', minecraft_color_vals.yellow],
    ['horn_coral_block', minecraft_color_vals.yellow],
    ['horn_coral_fan', minecraft_color_vals.yellow],
    ['bee_nest', minecraft_color_vals.yellow],
    ['bamboo_planks', minecraft_color_vals.yellow],
    ['bamboo_mosaic', minecraft_color_vals.yellow],
    ['bamboo_block[axis=y]', minecraft_color_vals.yellow],
    ['stripped_bamboo_block', minecraft_color_vals.yellow],
    ['bamboo_sign', minecraft_color_vals.yellow],
    ['bamboo_wall_sign', minecraft_color_vals.yellow],
    ['bamboo_hanging_sign', minecraft_color_vals.yellow],
    ['bamboo_wall_hanging_sign', minecraft_color_vals.yellow],
    ['bamboo_pressure_plate', minecraft_color_vals.yellow],
    ['bamboo_trapdoor', minecraft_color_vals.yellow],
    ['bamboo_stairs', minecraft_color_vals.yellow],
    ['bamboo_mosaic_stairs', minecraft_color_vals.yellow],
    ['bamboo_slab', minecraft_color_vals.yellow],
    ['bamboo_mosaic_slab', minecraft_color_vals.yellow],
    ['bamboo_fence_gate', minecraft_color_vals.yellow],
    ['bamboo_fence', minecraft_color_vals.yellow],
    ['bamboo_door', minecraft_color_vals.yellow],

    ['lime_wool', minecraft_color_vals.lime],
    ['lime_carpet', minecraft_color_vals.lime],
    ['lime_stained_glass', minecraft_color_vals.lime],
    ['lime_concrete', minecraft_color_vals.lime],
    ['lime_concrete_powder', minecraft_color_vals.lime],
    ['lime_glazed_terracotta', minecraft_color_vals.lime],
    ['lime_bed[part=foot]', minecraft_color_vals.lime],
    ['lime_shulker_box', minecraft_color_vals.lime],
    ['lime_candle', minecraft_color_vals.lime],
    ['melon', minecraft_color_vals.lime],

    ['pink_wool', minecraft_color_vals.pink],
    ['pink_carpet', minecraft_color_vals.pink],
    ['pink_stained_glass', minecraft_color_vals.pink],
    ['pink_concrete', minecraft_color_vals.pink],
    ['pink_concrete_powder', minecraft_color_vals.pink],
    ['pink_glazed_terracotta', minecraft_color_vals.pink],
    ['pink_bed[part=foot]', minecraft_color_vals.pink],
    ['pink_shulker_box', minecraft_color_vals.pink],
    ['pink_candle', minecraft_color_vals.pink],
    ['brain_coral', minecraft_color_vals.pink],
    ['brain_coral_block', minecraft_color_vals.pink],
    ['brain_coral_fan', minecraft_color_vals.pink],
    ['pearlescent_froglight', minecraft_color_vals.pink],
    ['cherry_sapling', minecraft_color_vals.pink],
    ['cherry_leaves', minecraft_color_vals.pink],

    ['gray_wool', minecraft_color_vals.gray],
    ['gray_carpet', minecraft_color_vals.gray],
    ['gray_stained_glass', minecraft_color_vals.gray],
    ['gray_concrete', minecraft_color_vals.gray],
    ['gray_concrete_powder', minecraft_color_vals.gray],
    ['gray_glazed_terracotta', minecraft_color_vals.gray],
    ['gray_bed[part=foot]', minecraft_color_vals.gray],
    ['gray_shulker_box', minecraft_color_vals.gray],
    ['gray_candle', minecraft_color_vals.gray],
    ['dead_tube_coral', minecraft_color_vals.gray],
    ['dead_tube_coral_block', minecraft_color_vals.gray],
    ['dead_tube_coral_fan', minecraft_color_vals.gray],
    ['dead_brain_coral', minecraft_color_vals.gray],
    ['dead_brain_coral_block', minecraft_color_vals.gray],
    ['dead_brain_coral_fan', minecraft_color_vals.gray],
    ['dead_bubble_coral', minecraft_color_vals.gray],
    ['dead_bubble_coral_block', minecraft_color_vals.gray],
    ['dead_bubble_coral_fan', minecraft_color_vals.gray],
    ['dead_fire_coral', minecraft_color_vals.gray],
    ['dead_fire_coral_block', minecraft_color_vals.gray],
    ['dead_fire_coral_fan', minecraft_color_vals.gray],
    ['dead_horn_coral', minecraft_color_vals.gray],
    ['dead_horn_coral_block', minecraft_color_vals.gray],
    ['dead_horn_coral_fan', minecraft_color_vals.gray],
    ['tinted_glass', minecraft_color_vals.gray],
    ['acacia_wood', minecraft_color_vals.gray],

    ['light_gray_wool', minecraft_color_vals.light_gray],
    ['light_gray_carpet', minecraft_color_vals.light_gray],
    ['light_gray_stained_glass', minecraft_color_vals.light_gray],
    ['light_gray_concrete', minecraft_color_vals.light_gray],
    ['light_gray_concrete_powder', minecraft_color_vals.light_gray],
    ['light_gray_glazed_terracotta', minecraft_color_vals.light_gray],
    ['light_gray_bed[part=foot]', minecraft_color_vals.light_gray],
    ['light_gray_shulker_box', minecraft_color_vals.light_gray],
    ['light_gray_candle', minecraft_color_vals.light_gray],
    ['structure_block', minecraft_color_vals.light_gray],
    ['jigsaw', minecraft_color_vals.light_gray],

    ['cyan_wool', minecraft_color_vals.cyan],
    ['cyan_carpet', minecraft_color_vals.cyan],
    ['cyan_stained_glass', minecraft_color_vals.cyan],
    ['cyan_concrete', minecraft_color_vals.cyan],
    ['cyan_concrete_powder', minecraft_color_vals.cyan],
    ['cyan_glazed_terracotta', minecraft_color_vals.cyan],
    ['cyan_bed[part=foot]', minecraft_color_vals.cyan],
    ['cyan_shulker_box', minecraft_color_vals.cyan],
    ['cyan_candle', minecraft_color_vals.cyan],
    ['prismarine', minecraft_color_vals.cyan],
    ['prismarine_slab', minecraft_color_vals.cyan],
    ['prismarine_stairs', minecraft_color_vals.cyan],
    ['prismarine_wall', minecraft_color_vals.cyan],
    ['warped_roots', minecraft_color_vals.cyan],
    ['warped_fungus', minecraft_color_vals.cyan],
    ['twisting_vines', minecraft_color_vals.cyan],
    ['nether_sprouts', minecraft_color_vals.cyan],
    ['sculk_sensor', minecraft_color_vals.cyan],
    ['calibrated_sculk_sensor', minecraft_color_vals.cyan],

    ['purple_wool', minecraft_color_vals.purple],
    ['purple_carpet', minecraft_color_vals.purple],
    ['purple_stained_glass', minecraft_color_vals.purple],
    ['purple_concrete', minecraft_color_vals.purple],
    ['purple_concrete_powder', minecraft_color_vals.purple],
    ['purple_glazed_terracotta', minecraft_color_vals.purple],
    ['purple_bed[part=foot]', minecraft_color_vals.purple],
    ['shulker_box', minecraft_color_vals.purple],
    ['purple_candle', minecraft_color_vals.purple],
    ['mycelium', minecraft_color_vals.purple],
    ['chorus_plant', minecraft_color_vals.purple],
    ['chorus_flower', minecraft_color_vals.purple],
    ['repeating_command_block', minecraft_color_vals.purple],
    ['bubble_coral', minecraft_color_vals.purple],
    ['bubble_coral_block', minecraft_color_vals.purple],
    ['bubble_coral_fan', minecraft_color_vals.purple],
    ['amethyst_block', minecraft_color_vals.purple],
    ['budding_amethyst', minecraft_color_vals.purple],
    ['small_amethyst_bud', minecraft_color_vals.purple],
    ['medium_amethyst_bud', minecraft_color_vals.purple],
    ['large_amethyst_bud', minecraft_color_vals.purple],
    ['amethyst_cluster', minecraft_color_vals.purple],

    ['blue_wool', minecraft_color_vals.blue],
    ['blue_carpet', minecraft_color_vals.blue],
    ['blue_stained_glass', minecraft_color_vals.blue],
    ['blue_concrete', minecraft_color_vals.blue],
    ['blue_concrete_powder', minecraft_color_vals.blue],
    ['blue_glazed_terracotta', minecraft_color_vals.blue],
    ['blue_bed[part=foot]', minecraft_color_vals.blue],
    ['blue_shulker_box', minecraft_color_vals.blue],
    ['blue_candle', minecraft_color_vals.blue],
    ['tube_coral', minecraft_color_vals.blue],
    ['tube_coral_block', minecraft_color_vals.blue],
    ['tube_coral_fan', minecraft_color_vals.blue],

    ['brown_wool', minecraft_color_vals.brown],
    ['brown_carpet', minecraft_color_vals.brown],
    ['brown_stained_glass', minecraft_color_vals.brown],
    ['brown_concrete', minecraft_color_vals.brown],
    ['brown_concrete_powder', minecraft_color_vals.brown],
    ['brown_glazed_terracotta', minecraft_color_vals.brown],
    ['brown_bed[part=foot]', minecraft_color_vals.brown],
    ['brown_shulker_box', minecraft_color_vals.brown],
    ['brown_candle', minecraft_color_vals.brown],
    ['dark_oak_log', minecraft_color_vals.brown],
    ['dark_oak_planks', minecraft_color_vals.brown],
    ['dark_oak_slab', minecraft_color_vals.brown],
    ['stripped_dark_oak_log', minecraft_color_vals.brown],
    ['dark_oak_wood', minecraft_color_vals.brown],
    ['stripped_dark_oak_wood', minecraft_color_vals.brown],
    ['dark_oak_sign', minecraft_color_vals.brown],
    ['dark_oak_wall_sign', minecraft_color_vals.brown],
    ['dark_oak_hanging_sign', minecraft_color_vals.brown],
    ['dark_oak_wall_hanging_sign', minecraft_color_vals.brown],
    ['dark_oak_pressure_plate', minecraft_color_vals.brown],
    ['dark_oak_trapdoor', minecraft_color_vals.brown],
    ['dark_oak_stairs', minecraft_color_vals.brown],
    ['dark_oak_fence_gate', minecraft_color_vals.brown],
    ['dark_oak_fence', minecraft_color_vals.brown],
    ['dark_oak_door', minecraft_color_vals.brown],
    ['spruce_log', minecraft_color_vals.brown],
    ['soul_sand', minecraft_color_vals.brown],
    ['soul_soil', minecraft_color_vals.brown],
    ['command_block', minecraft_color_vals.brown],
    ['brown_mushroom', minecraft_color_vals.brown],
    ['mud_brick_slab', minecraft_color_vals.brown],

    ['green_wool', minecraft_color_vals.green],
    ['green_carpet', minecraft_color_vals.green],
    ['green_stained_glass', minecraft_color_vals.green],
    ['green_concrete', minecraft_color_vals.green],
    ['green_concrete_powder', minecraft_color_vals.green],
    ['green_glazed_terracotta', minecraft_color_vals.green],
    ['green_bed[part=foot]', minecraft_color_vals.green],
    ['green_shulker_box', minecraft_color_vals.green],
    ['green_candle', minecraft_color_vals.green],
    ['end_portal_frame', minecraft_color_vals.green],
    ['chain_command_block', minecraft_color_vals.green],
    ['dried_kelp_block', minecraft_color_vals.green],
    ['sea_pickle', minecraft_color_vals.green],
    ['moss_carpet', minecraft_color_vals.green],
    ['moss_block', minecraft_color_vals.green],

    ['red_wool', minecraft_color_vals.red],
    ['red_carpet', minecraft_color_vals.red],
    ['red_stained_glass', minecraft_color_vals.red],
    ['red_concrete', minecraft_color_vals.red],
    ['red_concrete_powder', minecraft_color_vals.red],
    ['red_glazed_terracotta', minecraft_color_vals.red],
    ['red_bed[part=foot]', minecraft_color_vals.red],
    ['red_shulker_box', minecraft_color_vals.red],
    ['red_candle', minecraft_color_vals.red],
    ['bricks', minecraft_color_vals.red],
    ['brick_slab', minecraft_color_vals.red],
    ['brick_stairs', minecraft_color_vals.red],
    ['nether_wart', minecraft_color_vals.red],
    ['nether_wart_block', minecraft_color_vals.red],
    ['shroomlight', minecraft_color_vals.red],
    ['red_mushroom', minecraft_color_vals.red],
    ['red_mushroom_block', minecraft_color_vals.red],
    ['enchanting_table', minecraft_color_vals.red],
    ['fire_coral', minecraft_color_vals.red],
    ['fire_coral_block', minecraft_color_vals.red],
    ['fire_coral_fan', minecraft_color_vals.red],
    ['mangrove_log[axis=y]', minecraft_color_vals.red],
    ['mangrove_planks', minecraft_color_vals.red],
    ['mangrove_slab', minecraft_color_vals.red],
    ['stripped_mangrove_log', minecraft_color_vals.red],
    ['mangrove_wood', minecraft_color_vals.red],
    ['stripped_mangrove_wood', minecraft_color_vals.red],
    ['mangrove_sign', minecraft_color_vals.red],
    ['mangrove_wall_sign', minecraft_color_vals.red],
    ['mangrove_hanging_sign', minecraft_color_vals.red],
    ['mangrove_wall_hanging_sign', minecraft_color_vals.red],
    ['mangrove_pressure_plate', minecraft_color_vals.red],
    ['mangrove_trapdoor', minecraft_color_vals.red],
    ['mangrove_stairs', minecraft_color_vals.red],
    ['mangrove_fence_gate', minecraft_color_vals.red],
    ['mangrove_fence', minecraft_color_vals.red],
    ['mangrove_door', minecraft_color_vals.red],
    ['sniffer_egg', minecraft_color_vals.red],

    ['black_wool', minecraft_color_vals.black],
    ['black_carpet', minecraft_color_vals.black],
    ['black_stained_glass', minecraft_color_vals.black],
    ['black_concrete', minecraft_color_vals.black],
    ['black_concrete_powder', minecraft_color_vals.black],
    ['black_glazed_terracotta', minecraft_color_vals.black],
    ['black_bed[part=foot]', minecraft_color_vals.black],
    ['black_shulker_box', minecraft_color_vals.black],
    ['black_candle', minecraft_color_vals.black],
    ['coal_block', minecraft_color_vals.black],
    ['obsidian', minecraft_color_vals.black],
    ['crying_obsidian', minecraft_color_vals.black],
    ['blackstone', minecraft_color_vals.black],
    ['blackstone_slab', minecraft_color_vals.black],
    ['blackstone_stairs', minecraft_color_vals.black],
    ['blackstone_wall', minecraft_color_vals.black],
    ['polished_blackstone', minecraft_color_vals.black],
    ['polished_blackstone_slab', minecraft_color_vals.black],
    ['polished_blackstone_stairs', minecraft_color_vals.black],
    ['polished_blackstone_wall', minecraft_color_vals.black],
    ['polished_blackstone_bricks', minecraft_color_vals.black],
    ['polished_blackstone_brick_slab', minecraft_color_vals.black],
    ['polished_blackstone_brick_stairs', minecraft_color_vals.black],
    ['polished_blackstone_brick_wall', minecraft_color_vals.black],
    ['polished_blackstone_pressure_plate', minecraft_color_vals.black],
    ['chiseled_blackstone', minecraft_color_vals.black],
    ['gilded_blackstone', minecraft_color_vals.black],
    ['basalt', minecraft_color_vals.black],
    ['polished_basalt', minecraft_color_vals.black],
    ['smooth_basalt', minecraft_color_vals.black],
    ['ancient_debris', minecraft_color_vals.black],
    ['netherite_block', minecraft_color_vals.black],
    ['end_portal', minecraft_color_vals.black],
    ['end_gateway', minecraft_color_vals.black],
    ['dragon_egg', minecraft_color_vals.black],
    ['respawn_anchor', minecraft_color_vals.black],
    ['sculk', minecraft_color_vals.black],
    ['sculk_vein', minecraft_color_vals.black],
    ['sculk_catalyst', minecraft_color_vals.black],
    ['sculk_shrieker', minecraft_color_vals.black],

    ['gold_block', minecraft_color_vals.gold],
    ['light_weighted_pressure_plate', minecraft_color_vals.gold],
    ['raw_gold_block', minecraft_color_vals.gold],
    ['bell', minecraft_color_vals.gold],

    ['diamond_block', minecraft_color_vals.diamond],
    ['prismarine_bricks', minecraft_color_vals.diamond],
    ['prismarine_brick_slab', minecraft_color_vals.diamond],
    ['prismarine_brick_stairs', minecraft_color_vals.diamond],
    ['dark_prismarine', minecraft_color_vals.diamond],
    ['dark_prismarine_slab', minecraft_color_vals.diamond],
    ['dark_prismarine_stairs', minecraft_color_vals.diamond],
    ['beacon', minecraft_color_vals.diamond],
    ['conduit', minecraft_color_vals.diamond],

    ['lapis_block', minecraft_color_vals.lapis],

    ['emerald_block', minecraft_color_vals.emerald],

    ['spruce_log[axis=y]', minecraft_color_vals.spruce],
    ['spruce_planks', minecraft_color_vals.spruce],
    ['spruce_slab', minecraft_color_vals.spruce],
    ['stripped_spruce_log', minecraft_color_vals.spruce],
    ['spruce_wood', minecraft_color_vals.spruce],
    ['stripped_spruce_wood', minecraft_color_vals.spruce],
    ['spruce_sign', minecraft_color_vals.spruce],
    ['spruce_wall_sign', minecraft_color_vals.spruce],
    ['spruce_hanging_sign', minecraft_color_vals.spruce],
    ['spruce_pressure_plate', minecraft_color_vals.spruce],
    ['spruce_trapdoor', minecraft_color_vals.spruce],
    ['spruce_stairs', minecraft_color_vals.spruce],
    ['spruce_fence_gate', minecraft_color_vals.spruce],
    ['spruce_fence', minecraft_color_vals.spruce],
    ['spruce_door', minecraft_color_vals.spruce],
    ['oak_log', minecraft_color_vals.spruce],
    ['jungle_log', minecraft_color_vals.spruce],
    ['mangrove_log', minecraft_color_vals.spruce],
    ['podzol', minecraft_color_vals.spruce],
    ['campfire', minecraft_color_vals.spruce],
    ['soul_campfire', minecraft_color_vals.spruce],
    ['mangrove_roots', minecraft_color_vals.spruce],
    ['muddy_mangrove_roots', minecraft_color_vals.spruce],

    ['netherrack', minecraft_color_vals.netherrack],
    ['nether_bricks', minecraft_color_vals.netherrack],
    ['nether_brick_slab', minecraft_color_vals.netherrack],
    ['nether_brick_stairs', minecraft_color_vals.netherrack],
    ['nether_brick_wall', minecraft_color_vals.netherrack],
    ['nether_brick_fence', minecraft_color_vals.netherrack],
    ['chiseled_nether_bricks', minecraft_color_vals.netherrack],
    ['cracked_nether_bricks', minecraft_color_vals.netherrack],
    ['magma_block', minecraft_color_vals.netherrack],
    ['red_nether_bricks', minecraft_color_vals.netherrack],
    ['red_nether_brick_slab', minecraft_color_vals.netherrack],
    ['red_nether_brick_stairs', minecraft_color_vals.netherrack],
    ['red_nether_brick_wall', minecraft_color_vals.netherrack],
    ['nether_gold_ore', minecraft_color_vals.netherrack],
    ['nether_quartz_ore', minecraft_color_vals.netherrack],
    ['crimson_roots', minecraft_color_vals.netherrack],
    ['crimson_fungus', minecraft_color_vals.netherrack],
    ['weeping_vines', minecraft_color_vals.netherrack],

    ['white_terracotta', minecraft_color_vals.white_terracotta],
    ['calcite', minecraft_color_vals.white_terracotta],
    ['cherry_planks', minecraft_color_vals.white_terracotta],
    ['cherry_log[axis=y]', minecraft_color_vals.white_terracotta],
    ['stripped_cherry_log[axis=y]', minecraft_color_vals.white_terracotta],
    ['cherry_sign', minecraft_color_vals.white_terracotta],
    ['cherry_wall_sign', minecraft_color_vals.white_terracotta],
    ['cherry_pressure_plate', minecraft_color_vals.white_terracotta],
    ['cherry_trapdoor', minecraft_color_vals.white_terracotta],
    ['cherry_stairs', minecraft_color_vals.white_terracotta],
    ['cherry_slab', minecraft_color_vals.white_terracotta],
    ['cherry_fence_gate', minecraft_color_vals.white_terracotta],
    ['cherry_fence', minecraft_color_vals.white_terracotta],
    ['cherry_door', minecraft_color_vals.white_terracotta],

    ['orange_terracotta', minecraft_color_vals.orange_terracotta],
    ['magenta_terracotta', minecraft_color_vals.magenta_terracotta],
    ['light_blue_terracotta', minecraft_color_vals.light_blue_terracotta],
    ['yellow_terracotta', minecraft_color_vals.yellow_terracotta],
    ['lime_terracotta', minecraft_color_vals.lime_terracotta],

    ['pink_terracotta', minecraft_color_vals.pink_terracotta],
    ['stripped_cherry_log[axis=x]', minecraft_color_vals.pink_terracotta],
    ['stripped_cherry_log[axis=z]', minecraft_color_vals.pink_terracotta],
    ['stripped_cherry_wood', minecraft_color_vals.pink_terracotta],
    ['cherry_hanging_sign', minecraft_color_vals.pink_terracotta],
    ['cherry_wall_hanging_sign', minecraft_color_vals.pink_terracotta],

    ['gray_terracotta', minecraft_color_vals.gray_terracotta],
    ['tuff', minecraft_color_vals.gray_terracotta],
    ['cherry_wood', minecraft_color_vals.gray_terracotta],
    ['cherry_log[axis=x]', minecraft_color_vals.gray_terracotta],
    ['cherry_log[axis=z]', minecraft_color_vals.gray_terracotta],

    ['light_gray_terracotta', minecraft_color_vals.light_gray_terracotta],
    ['exposed_copper', minecraft_color_vals.light_gray_terracotta],
    ['exposed_cut_copper', minecraft_color_vals.light_gray_terracotta],
    ['exposed_cut_copper_slab', minecraft_color_vals.light_gray_terracotta],
    ['exposed_cut_copper_stairs', minecraft_color_vals.light_gray_terracotta],
    ['waxed_exposed_copper', minecraft_color_vals.light_gray_terracotta],
    ['waxed_exposed_cut_copper', minecraft_color_vals.light_gray_terracotta],
    ['waxed_exposed_cut_copper_slab', minecraft_color_vals.light_gray_terracotta],
    ['waxed_exposed_cut_copper_stairs', minecraft_color_vals.light_gray_terracotta],
    ['mud_bricks', minecraft_color_vals.light_gray_terracotta],
    ['mud_brick_stairs', minecraft_color_vals.light_gray_terracotta],
    ['mud_brick_wall', minecraft_color_vals.light_gray_terracotta],

    ['cyan_terracotta', minecraft_color_vals.cyan_terracotta],
    ['mud', minecraft_color_vals.cyan_terracotta],

    ['purple_terracotta', minecraft_color_vals.purple_terracotta],
    ['purple_shulker_box', minecraft_color_vals.purple_terracotta],

    ['blue_terracotta', minecraft_color_vals.blue_terracotta],

    ['brown_terracotta', minecraft_color_vals.brown_terracotta],
    ['dripstone_block', minecraft_color_vals.brown_terracotta],
    ['pointed_dripstone', minecraft_color_vals.brown_terracotta],

    ['green_terracotta', minecraft_color_vals.green_terracotta],
    ['red_terracotta', minecraft_color_vals.red_terracotta],
    ['black_terracotta', minecraft_color_vals.black_terracotta],

    ['crimson_nylium', minecraft_color_vals.crimson_nylium],

    ['crimson_stem', minecraft_color_vals.crimson_stem],
    ['stripped_crimson_stem', minecraft_color_vals.crimson_stem],
    ['crimson_planks', minecraft_color_vals.crimson_stem],
    ['crimson_slab', minecraft_color_vals.crimson_stem],
    ['crimson_sign', minecraft_color_vals.crimson_stem],
    ['crimson_wall_sign', minecraft_color_vals.crimson_stem],
    ['crimson_pressure_plate', minecraft_color_vals.crimson_stem],
    ['crimson_trapdoor', minecraft_color_vals.crimson_stem],
    ['crimson_stairs', minecraft_color_vals.crimson_stem],
    ['crimson_fence_gate', minecraft_color_vals.crimson_stem],
    ['crimson_fence', minecraft_color_vals.crimson_stem],
    ['crimson_door', minecraft_color_vals.crimson_stem],
    ['crimson_hanging_sign', minecraft_color_vals.crimson_stem],
    ['crimson_wall_hanging_sign', minecraft_color_vals.crimson_stem],

    ['crimson_hyphae', minecraft_color_vals.crimson_hyphae],
    ['stripped_crimson_hyphae', minecraft_color_vals.crimson_hyphae],

    ['warped_nylium', minecraft_color_vals.warped_nylium],
    ['oxidized_copper', minecraft_color_vals.warped_nylium],
    ['oxidized_cut_copper', minecraft_color_vals.warped_nylium],
    ['oxidized_cut_copper_slab', minecraft_color_vals.warped_nylium],
    ['oxidized_cut_copper_stairs', minecraft_color_vals.warped_nylium],
    ['waxed_oxidized_copper', minecraft_color_vals.warped_nylium],
    ['waxed_oxidized_cut_copper', minecraft_color_vals.warped_nylium],
    ['waxed_oxidized_cut_copper_slab', minecraft_color_vals.warped_nylium],
    ['waxed_oxidized_cut_copper_stairs', minecraft_color_vals.warped_nylium],

    ['warped_stem', minecraft_color_vals.warped_stem],
    ['stripped_warped_stem', minecraft_color_vals.warped_stem],
    ['warped_planks', minecraft_color_vals.warped_stem],
    ['warped_slab', minecraft_color_vals.warped_stem],
    ['warped_sign', minecraft_color_vals.warped_stem],
    ['warped_wall_sign', minecraft_color_vals.warped_stem],
    ['warped_pressure_plate', minecraft_color_vals.warped_stem],
    ['warped_trapdoor', minecraft_color_vals.warped_stem],
    ['warped_stairs', minecraft_color_vals.warped_stem],
    ['warped_fence_gate', minecraft_color_vals.warped_stem],
    ['warped_fence', minecraft_color_vals.warped_stem],
    ['warped_door', minecraft_color_vals.warped_stem],
    ['warped_hanging_sign', minecraft_color_vals.warped_stem],
    ['warped_wall_hanging_sign', minecraft_color_vals.warped_stem],
    ['weathered_copper', minecraft_color_vals.warped_stem],
    ['weathered_cut_copper', minecraft_color_vals.warped_stem],
    ['weathered_cut_copper_slab', minecraft_color_vals.warped_stem],
    ['weathered_cut_copper_stairs', minecraft_color_vals.warped_stem],
    ['waxed_weathered_copper', minecraft_color_vals.warped_stem],
    ['waxed_weathered_cut_copper', minecraft_color_vals.warped_stem],
    ['waxed_weathered_cut_copper_slab', minecraft_color_vals.warped_stem],
    ['waxed_weathered_cut_copper_stairs', minecraft_color_vals.warped_stem],

    ['warped_hyphae', minecraft_color_vals.warped_hyphae],
    ['stripped_warped_hyphae', minecraft_color_vals.warped_hyphae],

    ['warped_wart_block', minecraft_color_vals.warped_wart_block],

    ['deepslate', minecraft_color_vals.deepslate],
    ['deepslate_bricks', minecraft_color_vals.deepslate],
    ['deepslate_brick_slab', minecraft_color_vals.deepslate],
    ['deepslate_brick_stairs', minecraft_color_vals.deepslate],
    ['deepslate_brick_wall', minecraft_color_vals.deepslate],
    ['deepslate_tiles', minecraft_color_vals.deepslate],
    ['deepslate_tile_slab', minecraft_color_vals.deepslate],
    ['deepslate_tile_stairs', minecraft_color_vals.deepslate],
    ['deepslate_tile_wall', minecraft_color_vals.deepslate],
    ['cracked_deepslate_bricks', minecraft_color_vals.deepslate],
    ['cracked_deepslate_tiles', minecraft_color_vals.deepslate],
    ['chiseled_deepslate', minecraft_color_vals.deepslate],
    ['cobbled_deepslate', minecraft_color_vals.deepslate],
    ['cobbled_deepslate_slab', minecraft_color_vals.deepslate],
    ['cobbled_deepslate_stairs', minecraft_color_vals.deepslate],
    ['cobbled_deepslate_wall', minecraft_color_vals.deepslate],
    ['polished_deepslate', minecraft_color_vals.deepslate],
    ['polished_deepslate_slab', minecraft_color_vals.deepslate],
    ['polished_deepslate_stairs', minecraft_color_vals.deepslate],
    ['polished_deepslate_wall', minecraft_color_vals.deepslate],
    ['reinforced_deepslate', minecraft_color_vals.deepslate],
    ['deepslate_gold_ore', minecraft_color_vals.deepslate],
    ['deepslate_iron_ore', minecraft_color_vals.deepslate],
    ['deepslate_coal_ore', minecraft_color_vals.deepslate],
    ['deepslate_lapis_ore', minecraft_color_vals.deepslate],
    ['deepslate_diamond_ore', minecraft_color_vals.deepslate],
    ['deepslate_redstone_ore', minecraft_color_vals.deepslate],
    ['deepslate_emerald_ore', minecraft_color_vals.deepslate],
    ['deepslate_copper_ore', minecraft_color_vals.deepslate],
    ['infested_deepslate', minecraft_color_vals.deepslate],

    ['raw_iron_block', minecraft_color_vals.raw_iron_block],

    ['glow_lichen', minecraft_color_vals.glow_lichen],
    ['verdant_froglight', minecraft_color_vals.glow_lichen],

]);
