const sort_list = [
    "cobblestone*",
    "stone",
    "stone_*",
    "chiseled_stone*",
    "smooth_stone*",
    "mossy*",

    "sand*",
    "chiseled_sand*",
    "smooth_sand*",
    "red_sand*",
    "chiseled_red_sand*",
    "smooth_red_sand*",

    "glass",
    "glass_pane",
    "*_stained_glass",
    "*_stained_glass_pane",
    "tinted_glass",

    "*andesite*",
    "*diorite*",
    "*granite*",

    "cobbled_deepslate*",
    "*deepslate*",

    "*dirt*",
    "grass_block",
    "podzol",
    "mycelium",

    "netherrack",

    "soul_sand",
    "soul_soil",

    "basalt*",
    "*_basalt*",

    "prismarine*",
    "*prismarine*",

    "quartz*",
    "*quartz*",

    "blackstone*",
    "*blackstone*",

    "*obsidian",

    "ice",
    "*_ice",
    "snow*",

    "bricks",
    "brick_*",
    "nether_brick*",
    "*nether_brick*",

    "end_stone*",
    "*_end_stone*",
    "purpur*",

    "acacia*",
    "stripped_acacia*",
    "birch*",
    "stripped_birch*",
    "dark_oak*",
    "stripped_dark_oak*",
    "jungle*",
    "stripped_jungle*",
    "oak*",
    "stripped_oak*",
    "spruce*",
    "stripped_spruce*",

    "crimson*",
    "stripped_crimson*",
    "nether_wart*",
    "warped*",
    "stripped_warped*",

    "stick",

    "chest",
    "barrel",
    "*chest*",
    "*shulker_box",
    "scaffolding",

    "mushroom*",
    "*mushroom*",

    "*_ore",
    "iron_*",
    "*_iron*",
    "heavy_weighted_pressure_plate",
    "anvil",
    "*anvil",
    "chain",
    "coal_*",
    "*_coal*",
    "gold_*",
    "*_gold*",
    "light_weighted_pressure_plate",
    "copper_*",
    "*_copper*",
    "lapis_*",
    "*_lapis*",
    "diamond_*",
    "*_diamond*",
    "netherite_*",
    "*_netherite*",
    "ancient_debris",
    "amethyst*",
    "*_amethyst*",
    "emerald*",
    "*emerald*",

    "*rail",

    "*redstone*",
    "*piston*",
    "comparator",
    "repeater",
    "honey_block",
    "slime_block",
    "dispenser",
    "dropper",
    "hopper",
    "observer",
    "lever",
    "tripwire*",
    "note_block",
    "target",
    "tnt",

    "brewing_stand",
    "cake",
    "cauldron",
    "composter",

    "*torch",
    "*lantern",
    "*campfire",
    "glowstone",
    "sea_lantern",
    "shroomlight",
    "end_rod",
    "*candle",

    "*_wool",
    "*_carpet",

    "*concrete*",

    "clay",
    "terracotta",
    "*_terracotta",

    "*_banner",
    "*_bed",
    
    "grass*",
    "*grass",
    "fern*",
    "*fern",
    "azalea",
    "*azalea*",
    "moss*",
    "*dripleaf",
    "spore_blossom",
    "vines",
    "glow_lichen",
    "lily_pad",

    "allium",
    "azure_bluet",
    "blue_orchid",
    "cornflower",
    "dandelion",
    "lily_of_the_valley",
    "orange_tulip",
    "oxeye_daisy",
    "pink_tulip",
    "poppy",
    "red_tulip",
    "white_tulip",
    "wither_rose",

    "lilac",
    "peony",
    "rose_bush",
    "sunflower",

    "melon",
    "pumpkin",

    "*coral*",

    "sponge",
    "wet_sponge",
]
